const express = require("express");
const cors = require("cors");
const PORT = process.env.PORT || 5000;
const mysql = require("mysql2");
const jwt = require("jsonwebtoken");
const cookieParser = require("cookie-parser");
const bcrypt = require("bcryptjs")

//Creating our express entry app and as a method to handle all backend logic
const app = express();

const connection = mysql.createConnection({
  user: "root",
  host: "localhost",
  password: "",
  database: "ensure",
});

connection.connect((err) => {
  if (err) {
    console.log("Error when trying to connet to MySQL Server: ", err);
  } else {
    console.log("MySQL Server has been connected successfully");
  }
});

//Creating tables automatically when our server is started
const users = `CREATE TABLE IF NOT EXISTS users (
    userId INT PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR(40) NOT NULL,
    lastname VARCHAR(40) NOT NULL,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255)
)`;

connection.query(users, (err) => {
  if (err) {
    console.log("Error while trying to create USERS Table: ", err);
  } else {
    console.log("USERS Table was created!");
  }
});

//Middleware to pre-process frontend request origins
app.use(
  cors({
    origin: "http://localhost:5173",
    //Setting cors to enable requests with token in headers
    withCredentials: true,
  }),
);

app.use(express.json());
app.use(cookieParser());

app.get("/", (req, res) => {
  res.send(
    "ENSURE Database is running and already waiting for client requests...",
  );
});

const JWT_SECRET = "kajsfdioasfnjkasndfoiasfnksdnfdskjfnlanvjisdndskf";

//function to generate token for the user in auth middleware
function generateToken(user) {
  return jwt.sign(
    {
      userId: user.userId,
      email: user.email,
    },
    JWT_SECRET,
    { expiresIn: "7d" },
  );
}

//Validating if the token from frontend request has been generated by our recently
app.get("/api/verify-token", async (req, res) => {
  const token = req.cookies.token;
  if (!token) return res.status(401).json({ isOkay: false });

  jwt.verify(token, JWT_SECRET, (err, decoded) => {
    if (err) return res.json({ isOkay: false });
    res.json({ isOkay: true, user: decoded });
  });
});

function authorize(req, res, next) {
  const token = req.cookies.token;
  if (!token) {
    return res.status(401).json({
      message: "Ooops! There is no token provided in request headers",
    });
  }

  jwt.verify(token, JWT_SECRET, (err, extracted) => {
    if (err) {
      console.log("Error while trying to verify user token");
      res.status(403).json({ message: "This token was malformed!" });
    }
    req.user = extracted;
    next();
  });
}

//Authentication functions
app.post("/api/users/register", async (req, res) => {
  const { firstname, lastname, email, password } = req.body;
  try {
    const [existingUser] = await connection.promise().query(`SELECT * FROM users WHERE email=?`, [email], (err) => {
        if(err){
            console.log("Error while trying to fetch for existing user: ", err)
        }
    })
    if(existingUser.length > 0){
        return res.status(400).json({message: "User with this email already exists"})
    }

    //Hashing password
    const salt = await bcrypt.genSalt(10)
    const hashedPassword = await bcrypt.hash(password, salt)

    const sql = `INSERT INTO users (firstname, lastname, email, password) VALUES(?, ?, ?, ?)`;
    connection.promise().query(sql, [firstname, lastname, email, hashedPassword], (err) => {
        if(err){
            
            console.log("Server error during running query to register new client: ", err)
            return res.status(500).json({message: "Ooops! Try again after a moment because server has got unexpected error"})
        }
    })
    return res.status(201).json({message: "User account was created successfully"})
  } catch (err) {
    console.log("Error while trying to register new user: ", err)
    return res.status(500).json({message: "Internal Server during registration process"})
  }
});

//Logging system activities for auditing and monitoring purposes



app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
